import React from "react";

const initialState = {
  products: [
    {
      id: 1,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_coffee.png",
      aroma: "coffee",
      volume: 200,
      price: 9.9,
    },
    {
      id: 2,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "chocolate",
      volume: 200,
      price: 9.9,
    },
    {
      id: 3,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "cranbery",
      volume: 200,
      price: 9.9,
    },
    {
      id: 4,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "mango",
      volume: 200,
      price: 9.9,
    },
    {
      id: 5,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "strawberry",
      volume: 200,
      price: 9.9,
    },
    {
      id: 6,
      category: "salt scrubs",
      title: "Salt body scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "lemongrass",
      volume: 200,
      price: 9.9,
    },
    {
      id: 7,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_coffee.png",
      aroma: "coffee",
      volume: 200,
      price: 9.9,
    },
    {
      id: 8,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "chocolate",
      volume: 200,
      price: 9.9,
    },
    {
      id: 9,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "cranbery",
      volume: 200,
      price: 9.9,
    },
    {
      id: 10,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "mango",
      volume: 200,
      price: 9.9,
    },
    {
      id: 11,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "strawberry",
      volume: 200,
      price: 9.9,
    },
    {
      id: 12,
      category: "sugar scrubs",
      title: "Sugar Scrub",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "lemongrass",
      volume: 200,
      price: 9.9,
    },
    {
      id: 13,
      category: "oils",
      title: "Essential Oil",
      img: "/img/scrub_salt/scrub_chocolate.png",
      aroma: "lemongrass",
      volume: 200,
      price: 9.9,
    },
  ],
  cart: [],
  keyword: "",
};

export default React.createContext(initialState);
